import geopandas as gpd
import os

from synthesize import synthesize

# Load our powerplants geodataframe.
ca_power_plants = gpd.read_file(
    os.path.abspath("examples/sjoin/data/ca-powerplants.geojson")
)

# Restrict our input to the synthesizer to a subset of each table.
# In this example, we just take the first 100 powerplants.
input_ca_power_plants = ca_power_plants.head(100)

# Our target output would match the output generated by actually running the target program.
target = input_ca_power_plants.dissolve(by="County")


input_gdfs = {
    "ca_power_plants": input_ca_power_plants,
}

synthesize(input_gdfs, target)
